name: Publish

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
    
      - name: SETUP .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
    
      - name: Restore
        run: dotnet restore ./encoratest.sln
    
      - name: Build
        run: dotnet build ./encoratest.sln --configuration Release --no-restore
    
      - name: Publish
        run: dotnet publish ./encoratest.sln --configuration Release --no-build --output './publish'

      - name: Deployment
        uses: azure/webapps-deploy@v3
        with: 
          app-name: azuretest1234
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './publish'
